// <auto-generated />
using System;
using AssinanteAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssinanteAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssinanteAPI.Domain.Entities.Assinante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInicioAssinatura")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Plano")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("ValorMensal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Assinantes_Email");

                    b.ToTable("Assinantes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataInicioAssinatura = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joao.silva@email.com",
                            NomeCompleto = "João Silva",
                            Plano = 1,
                            Status = 1,
                            ValorMensal = 29.90m
                        },
                        new
                        {
                            Id = 2,
                            DataInicioAssinatura = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria.santos@email.com",
                            NomeCompleto = "Maria Santos",
                            Plano = 2,
                            Status = 1,
                            ValorMensal = 49.90m
                        },
                        new
                        {
                            Id = 3,
                            DataInicioAssinatura = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pedro.costa@email.com",
                            NomeCompleto = "Pedro Costa",
                            Plano = 3,
                            Status = 1,
                            ValorMensal = 99.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
